[2025-08-17T09:00:56.727+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T09:00:56.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-17T09:00:55.587877+00:00 [queued]>
[2025-08-17T09:00:56.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-17T09:00:55.587877+00:00 [queued]>
[2025-08-17T09:00:56.755+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T09:00:56.762+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-08-17 09:00:55.587877+00:00
[2025-08-17T09:00:56.765+0000] {standard_task_runner.py:64} INFO - Started process 432 to run task
[2025-08-17T09:00:56.767+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_pipeline', 'dbt_run', 'manual__2025-08-17T09:00:55.587877+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpvek7j7vp']
[2025-08-17T09:00:56.768+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask dbt_run
[2025-08-17T09:00:56.802+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_pipeline.dbt_run manual__2025-08-17T09:00:55.587877+00:00 [running]> on host eb1b0a67a168
[2025-08-17T09:00:56.874+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T09:00:55.587877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T09:00:55.587877+00:00'
[2025-08-17T09:00:56.874+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T09:00:56.885+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-17T09:00:56.886+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /Users/ahmedwael/Documents/piplines/my_dbt_project && dbt run']
[2025-08-17T09:00:56.891+0000] {subprocess.py:86} INFO - Output:
[2025-08-17T09:00:56.892+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /Users/ahmedwael/Documents/piplines/my_dbt_project: No such file or directory
[2025-08-17T09:00:56.892+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-17T09:00:56.893+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T09:00:56.903+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-17T09:00:56.906+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_pipeline, task_id=dbt_run, run_id=manual__2025-08-17T09:00:55.587877+00:00, execution_date=20250817T090055, start_date=20250817T090056, end_date=20250817T090056
[2025-08-17T09:00:56.914+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 432)
[2025-08-17T09:00:56.948+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-17T09:00:56.968+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-17T09:00:56.972+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
