[2025-08-18T07:07:47.404+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T07:07:47.426+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-18T07:06:58.070568+00:00 [queued]>
[2025-08-18T07:07:47.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-18T07:06:58.070568+00:00 [queued]>
[2025-08-18T07:07:47.431+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-18T07:07:47.441+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-08-18 07:06:58.070568+00:00
[2025-08-18T07:07:47.444+0000] {standard_task_runner.py:64} INFO - Started process 201 to run task
[2025-08-18T07:07:47.447+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_pipeline', 'dbt_run', 'manual__2025-08-18T07:06:58.070568+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpx5x0jiy4']
[2025-08-18T07:07:47.448+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask dbt_run
[2025-08-18T07:07:47.483+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_pipeline.dbt_run manual__2025-08-18T07:06:58.070568+00:00 [running]> on host dd44a0560791
[2025-08-18T07:07:47.542+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T07:06:58.070568+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T07:06:58.070568+00:00'
[2025-08-18T07:07:47.542+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T07:07:47.565+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T07:07:47.566+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/my_dbt_project && dbt run']
[2025-08-18T07:07:47.570+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T07:07:47.571+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-08-18T07:07:47.572+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-08-18T07:07:47.572+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T07:07:47.580+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-18T07:07:47.582+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_pipeline, task_id=dbt_run, run_id=manual__2025-08-18T07:06:58.070568+00:00, execution_date=20250818T070658, start_date=20250818T070747, end_date=20250818T070747
[2025-08-18T07:07:47.589+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 201)
[2025-08-18T07:07:47.629+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-18T07:07:47.645+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T07:07:47.648+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
