[2025-08-17T21:36:39.247+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T21:36:39.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-17T21:36:38.277361+00:00 [queued]>
[2025-08-17T21:36:39.305+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-17T21:36:38.277361+00:00 [queued]>
[2025-08-17T21:36:39.305+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T21:36:39.316+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-08-17 21:36:38.277361+00:00
[2025-08-17T21:36:39.322+0000] {standard_task_runner.py:64} INFO - Started process 1790 to run task
[2025-08-17T21:36:39.327+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_pipeline', 'dbt_run', 'manual__2025-08-17T21:36:38.277361+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpe8rq5zzr']
[2025-08-17T21:36:39.330+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask dbt_run
[2025-08-17T21:36:39.383+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_pipeline.dbt_run manual__2025-08-17T21:36:38.277361+00:00 [running]> on host eb1b0a67a168
[2025-08-17T21:36:39.460+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T21:36:38.277361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T21:36:38.277361+00:00'
[2025-08-17T21:36:39.460+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T21:36:39.475+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-17T21:36:39.478+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /Users/ahmedwael/Documents/piplines/my_dbt_project && dbt run']
[2025-08-17T21:36:39.493+0000] {subprocess.py:86} INFO - Output:
[2025-08-17T21:36:39.495+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /Users/ahmedwael/Documents/piplines/my_dbt_project: No such file or directory
[2025-08-17T21:36:39.495+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-17T21:36:39.496+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T21:36:39.508+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-17T21:36:39.512+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_pipeline, task_id=dbt_run, run_id=manual__2025-08-17T21:36:38.277361+00:00, execution_date=20250817T213638, start_date=20250817T213639, end_date=20250817T213639
[2025-08-17T21:36:39.522+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 1790)
[2025-08-17T21:36:39.546+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-17T21:36:39.569+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-17T21:36:39.572+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
