[2025-08-17T09:00:53.571+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T09:00:53.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run scheduled__2025-08-16T00:00:00+00:00 [queued]>
[2025-08-17T09:00:53.599+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run scheduled__2025-08-16T00:00:00+00:00 [queued]>
[2025-08-17T09:00:53.599+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T09:00:53.607+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-08-16 00:00:00+00:00
[2025-08-17T09:00:53.609+0000] {standard_task_runner.py:64} INFO - Started process 429 to run task
[2025-08-17T09:00:53.612+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_pipeline', 'dbt_run', 'scheduled__2025-08-16T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpv8hzrujb']
[2025-08-17T09:00:53.614+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask dbt_run
[2025-08-17T09:00:53.655+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_pipeline.dbt_run scheduled__2025-08-16T00:00:00+00:00 [running]> on host eb1b0a67a168
[2025-08-17T09:00:53.736+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-16T00:00:00+00:00'
[2025-08-17T09:00:53.737+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T09:00:53.766+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-17T09:00:53.767+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /Users/ahmedwael/Documents/piplines/my_dbt_project && dbt run']
[2025-08-17T09:00:53.772+0000] {subprocess.py:86} INFO - Output:
[2025-08-17T09:00:53.774+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /Users/ahmedwael/Documents/piplines/my_dbt_project: No such file or directory
[2025-08-17T09:00:53.774+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-17T09:00:53.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T09:00:53.785+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-17T09:00:53.788+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_pipeline, task_id=dbt_run, run_id=scheduled__2025-08-16T00:00:00+00:00, execution_date=20250816T000000, start_date=20250817T090053, end_date=20250817T090053
[2025-08-17T09:00:53.799+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 429)
[2025-08-17T09:00:53.838+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-17T09:00:53.857+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-17T09:00:53.860+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
