[2025-08-18T07:08:04.478+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T07:08:04.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-18T07:08:04.292662+00:00 [queued]>
[2025-08-18T07:08:04.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.dbt_run manual__2025-08-18T07:08:04.292662+00:00 [queued]>
[2025-08-18T07:08:04.507+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-18T07:08:04.515+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-08-18 07:08:04.292662+00:00
[2025-08-18T07:08:04.517+0000] {standard_task_runner.py:64} INFO - Started process 204 to run task
[2025-08-18T07:08:04.520+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_pipeline', 'dbt_run', 'manual__2025-08-18T07:08:04.292662+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpihpoj3cc']
[2025-08-18T07:08:04.521+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask dbt_run
[2025-08-18T07:08:04.558+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_pipeline.dbt_run manual__2025-08-18T07:08:04.292662+00:00 [running]> on host dd44a0560791
[2025-08-18T07:08:04.638+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T07:08:04.292662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T07:08:04.292662+00:00'
[2025-08-18T07:08:04.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T07:08:04.649+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T07:08:04.650+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/my_dbt_project && dbt run']
[2025-08-18T07:08:04.656+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T07:08:04.656+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-08-18T07:08:04.657+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-08-18T07:08:04.657+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T07:08:04.666+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-18T07:08:04.668+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_pipeline, task_id=dbt_run, run_id=manual__2025-08-18T07:08:04.292662+00:00, execution_date=20250818T070804, start_date=20250818T070804, end_date=20250818T070804
[2025-08-18T07:08:04.676+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 204)
[2025-08-18T07:08:04.701+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-18T07:08:04.718+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T07:08:04.721+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
